apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - image: aksdemoccr.azurecr.io/demos/skaffold-spring-boot-example
      jib: {}
  local: {}

deploy:
  kubectl:
    manifests:
      - k8s-*