apiVersion: v1
kind: Service
metadata:
  name: aksdemo-app-service
  labels:
    app: aksdemo-app
spec:
  type: LoadBalancer
  selector:
    app: aksdemo-app
  ports:
    - port: 80
      targetPort: 8080
